# Server
server.port=${PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://your-neon-hostname:5432/your-db-name?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:your-username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your-password}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=2

# Razorpay
razorpay.key_id=${RAZORPAY_KEY_ID:your-razorpay-key-id}
razorpay.key_secret=${RAZORPAY_SECRET:your-razorpay-secret}

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}