
# Server
server.port=${PORT:8080}

# Neon PostgreSQL
spring.datasource.url=${jdbc:postgresql://ep-shiny-sky-a1135578-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${neondb_owner}
spring.datasource.password=${npg_P8xfIn3ukhET}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=2

# Razorpay
razorpay.key_id=${zp_test_SM33QLRIjoFWJG}
razorpay.key_secret=${4ulYdqFCLZK1lQP2HYq4QMO8}

