# Local Development Properties

# Replace these with your actual Neon PostgreSQL credentials
spring.datasource.url=jdbc:postgresql://ep-shiny-sky-a1l35578-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_P8xfIn3ukhET&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_P8xfIn3ukhET

# Razorpay credentials
razorpay.key_id=rzp_test_SMq92ddEmYY3qS
razorpay.key_secret=ohJ62aSmgvSBc0Cx4MZbdeAj

# JWT Secret
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
